services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 3001:3001
    env_file: ./server/.env

  client:
    build:
      context: ./client/my-app
    # This will force server service to build and start before client.
    depends_on:
      - server
    volumes:
      - ./client/my-app:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"